build:
  maxIssues: 10

complexity:
  active: true
  LongMethod:
    active: true
    threshold: 30
  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 6

style:
  active: true
  MagicNumber:
    active: true
    excludes: ["FontSize", "Alpha"]
  NewLineAtEndOfFile:
    active: true
  MaxLineLength:
    active: true
    maxLineLength: 120