build:
  maxIssues: 0
  weights:
    complexity: 2
    LongParameterList: 1
    style: 1
    comments: 0

detekt:
  config:
    validation: true

processors:
  active: true
  excludes: "**/test/**,**/androidTest/**"

complexity:
  active: true
  LongMethod:
    active: true
    threshold: 30
  LongParameterList:
    active: true
    threshold: 6

style:
  active: true
  MagicNumber:
    active: true
    excludes: ["FontSize", "Alpha", "Percentage"]
  NewLineAtEndOfFile:
    active: true
  MaxLineLength:
    active: true
    maxLineLength: 120
    excludeCommentStatements: true